### ISSUE TITLE
Option to display hidden screen-reader content

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#621]
Marked as question as I'm not sure if this is a good idea or not. Was playing with an idea to show content hidden for screen-readers only as well as strike-through content that won't be read.

Using this CSS:

```css
.for-screen-reader-only {
	position: static !important;
	width: inherit !important;
	height: inherit !important;
	color: red !important;
	font-family: Arial, Helvetica, sans-serif !important;
	display: inline-block !important;
	background: white !important;
	font-weight: bold !important;
}
*[aria-hidden="true"] {
	opacity: 0.3 !important;
	text-decoration: line-through;
}
*[aria-label]:after {
	content: attr(aria-label);
	color: red !important;
	font-family: Arial, Helvetica, sans-serif !important;
	display: inline-block !important;
	background: white !important;
	font-weight: bold !important;
}
*:focus {
	outline: 6px solid cyan !important;
}
```

It ends up looking like this:

![screenshot 2018-10-29 16 53 56](https://user-images.githubusercontent.com/73479/47680264-b6059380-db9c-11e8-8dcf-cc280354ed08.png)

Obviously it looks rough but I think that would be acceptable. A pure CSS solution probably won't work as there is no way to display alt tags through CSS only. But perhaps we could have some sort of system-wide toggle. I could see this display mode being useful for an author who may not be familiar with screen-reader software to get a rough idea of what a visually impaired student "sees".

Feedback welcome.
