### ISSUE TITLE
Implement hanging indent

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#769]
Maybe Related: #582

For citations we need hanging indents. Here's a screenshot of a flash widget used for this purpose in a module built in the old system:

![image](https://user-images.githubusercontent.com/73479/55483673-150c8000-55f5-11e9-9435-a304190a16e1.png)

**Comment by iturgeon** [comment]
style wise, I think this trick should work:
```css
.hanging-indent {
  text-indent: -25px;
  padding-left: 25px;
}
```

I have questions about how you see this being implemented.  I'm not sure if we need a new chunk type or if this is something that can be used in styleList
